apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: weather-processor-service
  name: weather-processor-service
spec:
  type: ClusterIP
  ports:
    - name: "4444"
      port: 4444
      targetPort: 4444
  selector:
    io.kompose.service: weather-processor-service
status:
  loadBalancer: {}
