apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: weather-alert-service
  name: weather-alert-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: weather-alert-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/weatherapp-my-network: "true"
        io.kompose.service: weather-alert-service
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://registration-service:8761/eureka/
            - name: SPRING_DATA_REDIS_HOST
              value: redis-master
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
          image: gcr.io/dissertation-437908/weather-alert-service:latest
          name: weather-alert-service
          ports:
            - containerPort: 6666
              hostPort: 6666
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
